language: php

php:
  - "7.2"

services:
  - mysql

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - composer run-script test
  - composer run-script lint
